version: "3"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker containers:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
services:

  nginx:
    image: app_nginx:latest
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-file: 4
        max-size: 256m
    volumes:
      - django_staticfiles:/__staticfiles:ro
      - nginx_letsencrypt:/etc/letsencrypt:rw
    env_file:
      - ../secrets/nginx.env
    depends_on:
      - django
    ports:
      - 80:8080
      - 443:4443
    networks:
      - app_frontend_network

  django:
    image: app_django:latest
    restart: unless-stopped
    container_name: django
    logging:
      driver: "json-file"
      options:
        max-file: 4
        max-size: 256m
    volumes:
      - django_staticfiles:/app/__staticfiles:rw
    env_file:
      - ../secrets/redis.env
      - ../secrets/django.env
      - ../secrets/postgres.env
    depends_on:
      - postgres
      - redis
    networks:
      - app_frontend_network
      - app_backend_network

  redis:
    image: app_redis:latest
    restart: unless-stopped
    container_name: redis
    logging:
      driver: "json-file"
      options:
        max-file: 4
        max-size: 256m
    volumes:
      - redis_data:/data:rw
    env_file:
      - ../secrets/redis.env
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - app_backend_network

  postgres:
    image: app_postgres:latest
    restart: unless-stopped
    container_name: postgres
    logging:
      driver: "json-file"
      options:
        max-file: 4
        max-size: 256m
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - ../secrets/postgres.env
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - app_backend_network

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker networks:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
networks:

  app_frontend_network:
    driver: bridge

  app_backend_network:
    driver: bridge

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker volumes:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
volumes:

  redis_data:

  postgres_data:

  nginx_letsencrypt:

  django_staticfiles:
