version: "3.8"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker containers:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
services:

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    volumes:
      - redis_data:/data
    env_file:
      - ../secrets/redis.env
    ports:
      - 6379:6379
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
      - app_staticfiles:/staticfiles
    env_file:
      - ../secrets/nginx.env
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - app_network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../secrets/postgres.env
    ports:
      - 5432:5432
    networks:
      - app_network

  app:
    image: app:latest
    restart: unless-stopped
    container_name: app
    volumes:
      - app_staticfiles:/app/staticfiles
    env_file:
      - ../secrets/app.env
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    networks:
      - app_network

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker networks:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

networks:

  app_network:
    driver: bridge

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker volumes:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

volumes:

  redis_data:
  postgres_data:
  app_staticfiles:
