version: "3"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker containers:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
services:

  nginx:
    image: app_nginx:latest
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "256m"
    volumes:
      - django_staticfiles:/__staticfiles:ro
      - nginx_letsencrypt:/etc/letsencrypt:rw
    env_file:
      - ../secrets/nginx.env
    depends_on:
      - django
    ports:
      - 80:8080
      - 443:4443
    networks:
      app_frontend_network:
        ipv4_address: 192.168.10.10

  django:
    image: app_django:latest
    restart: unless-stopped
    container_name: django
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "256m"
    volumes:
      - django_staticfiles:/app/__staticfiles:rw
    env_file:
      - ../secrets/redis.env
      - ../secrets/django.env
      - ../secrets/postgres.env
    depends_on:
      - postgres
      - redis
    networks:
      app_frontend_network:
        ipv4_address: 192.168.10.11
      app_backend_network:
        ipv4_address: 192.168.20.11

  redis:
    image: app_redis:latest
    restart: unless-stopped
    container_name: redis
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "256m"
    volumes:
      - redis_data:/data:rw
    env_file:
      - ../secrets/redis.env
    networks:
      app_backend_network:
        ipv4_address: 192.168.20.12

  postgres:
    image: app_postgres:latest
    restart: unless-stopped
    container_name: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "256m"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - ../secrets/postgres.env
    networks:
      app_backend_network:
        ipv4_address: 192.168.20.13

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker networks:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
networks:

  app_frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        subnet: 192.168.10.0/24

  app_backend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        subnet: 192.168.20.0/24

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# docker volumes:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
volumes:

  redis_data:

  postgres_data:

  nginx_letsencrypt:

  django_staticfiles:
